# Generated by Django 4.2 on 2023-08-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTraductor', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('apellidoPaternoTraductor', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellidoMaternoTraductor', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('delExtanjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='TestigoUno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTestigoUno', models.CharField(max_length=50, verbose_name='Nombre del primer testigo')),
                ('apellidoPaternoTestigoUno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellidoMaternoTestigoUno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('firmaTestigoUno', models.BinaryField(verbose_name='Firma')),
                ('huellaTestigoUno', models.BinaryField(verbose_name='Huella')),
                ('delExtanjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
        migrations.CreateModel(
            name='TestigoDos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTestigoDos', models.CharField(max_length=50, verbose_name='Nombre del Segundo testigo')),
                ('apellidoPaternoTestigoDos', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellidoMaternoTestigoDos', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('firmaTestigoDos', models.BinaryField(verbose_name='Firma')),
                ('huellaTestigoDos', models.BinaryField(verbose_name='Huella')),
                ('delExtanjero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
        ),
    ]
