# Generated by Django 4.2 on 2023-08-17 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extranjero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('horaRegistro', models.DateTimeField(auto_now_add=True)),
                ('numeroExtranjero', models.CharField(max_length=10, unique=True)),
                ('nombreExtranjero', models.CharField(blank=True, max_length=50)),
                ('apellidoPaternoExtranjero', models.CharField(blank=True, max_length=50)),
                ('apellidoMaternoExtranjero', models.CharField(blank=True, max_length=50)),
                ('genero', models.IntegerField(choices=[[0, 'HOMBRE'], [1, 'MUJER']])),
                ('fechaNacimiento', models.DateField()),
                ('documentoIdentidad', models.FileField(blank=True, null=True, upload_to='files/')),
                ('viajaSolo', models.BooleanField()),
                ('tipoEstancia', models.CharField(blank=True, max_length=50)),
                ('deLaEstacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.estacion', verbose_name='Estacion de Origen')),
            ],
            options={
                'verbose_name_plural': 'Extranjeros',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nacionalidad')),
                ('Abreviatura', models.CharField(max_length=200, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='Biometrico',
            fields=[
                ('Extranjero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vigilancia.extranjero')),
                ('fotografiaExtranjero', models.FileField(blank=True, null=True, upload_to='files/')),
                ('fechaHoraFotografia', models.DateTimeField(auto_now_add=True)),
                ('huellaExtranjero', models.FileField(blank=True, null=True, upload_to='files/')),
                ('fechaHoraHuella', models.DateTimeField(auto_now_add=True)),
                ('firmaExtranjero', models.FileField(blank=True, null=True, upload_to='', verbose_name='files/')),
                ('fechaHoraFirma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Biometricos',
            },
        ),
        migrations.CreateModel(
            name='PuestaDisposicionINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.CharField(max_length=50)),
                ('fechaOficio', models.DateField()),
                ('nombreAutoridadSignaUno', models.CharField(max_length=100)),
                ('cargoAutoridadSignaUno', models.CharField(max_length=100)),
                ('nombreAutoridadSignaDos', models.CharField(max_length=100)),
                ('cargoAutoridadSignaDos', models.CharField(max_length=100)),
                ('oficioPuesta', models.FileField(blank=True, null=True, upload_to='files/')),
                ('oficioComision', models.FileField(blank=True, null=True, upload_to='files/')),
                ('puntoRevision', models.CharField(max_length=100)),
                ('deLaEstacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.estacion')),
            ],
            options={
                'verbose_name_plural': 'Puestas a Disposición INM',
            },
        ),
        migrations.CreateModel(
            name='PuestaDisposicionAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.CharField(max_length=50)),
                ('fechaOficio', models.DateField()),
                ('nombreAutoridadSignaUno', models.CharField(max_length=100)),
                ('cargoAutoridadSignaUno', models.CharField(max_length=100)),
                ('nombreAutoridadSignaDos', models.CharField(max_length=100)),
                ('cargoAutoridadSignaDos', models.CharField(max_length=100)),
                ('oficioPuesta', models.FileField(blank=True, null=True, upload_to='files/')),
                ('oficioComision', models.FileField(blank=True, null=True, upload_to='files/')),
                ('puntoRevision', models.CharField(max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('numeroCarpeta', models.IntegerField()),
                ('entidadFederativa', models.CharField(max_length=100)),
                ('certificadoMedico', models.FileField(blank=True, null=True, upload_to='files/')),
                ('deLaEstacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.estacion', verbose_name='Estación de origen')),
            ],
            options={
                'verbose_name_plural': 'Puestas a Disposicion AC',
            },
        ),
        migrations.AddField(
            model_name='extranjero',
            name='deLaPuestaAC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extranjeros', to='vigilancia.puestadisposicionac', verbose_name='Puesta'),
        ),
        migrations.AddField(
            model_name='extranjero',
            name='deLaPuestaIMN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extranjeros', to='vigilancia.puestadisposicioninm', verbose_name='Puesta'),
        ),
        migrations.AddField(
            model_name='extranjero',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.nacionalidad', verbose_name='Nacionalidad'),
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delExtranjero', models.IntegerField()),
                ('relacion', models.IntegerField(choices=[[0, 'ESPOSO(A)'], [1, 'HIJO(A)'], [2, 'MADRE'], [3, 'PADRE'], [4, 'OTRO']])),
                ('delAcompanante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
            options={
                'verbose_name_plural': 'Acompañantes',
            },
        ),
    ]
