# Generated by Django 4.2 on 2023-08-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nacionalidad')),
                ('Abreviatura', models.CharField(max_length=200, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='PuestaDisposicionINM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.CharField(max_length=50)),
                ('fechaOficio', models.DateField()),
                ('nombreAutoridadSigna', models.CharField(max_length=100)),
                ('cargoAutoridadSigna', models.CharField(max_length=100)),
                ('oficioPuesta', models.FileField(blank=True, null=True, upload_to='files')),
                ('oficioComision', models.FileField(blank=True, null=True, upload_to='files')),
                ('puntoRevision', models.CharField(max_length=100)),
                ('deLaEstacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.estacion')),
            ],
            options={
                'verbose_name_plural': 'Puestas a Disposición INM',
            },
        ),
        migrations.CreateModel(
            name='PuestaDisposicionAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOficio', models.IntegerField()),
                ('fechaOficio', models.DateField()),
                ('nombreAutoridadSigna', models.CharField(max_length=100)),
                ('cargoAutoridadSigna', models.CharField(max_length=100)),
                ('oficioPuesta', models.FileField(blank=True, null=True, upload_to='files')),
                ('oficioComision', models.FileField(blank=True, null=True, upload_to='files')),
                ('puntoRevision', models.CharField(max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('numeroCarpeta', models.IntegerField()),
                ('entidadFederativa', models.CharField(max_length=100)),
                ('certificadoMedico', models.FileField(blank=True, null=True, upload_to='files')),
                ('deLaEstacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.estacion')),
            ],
            options={
                'verbose_name_plural': 'Puestas a Disposicion AC',
            },
        ),
        migrations.CreateModel(
            name='Extranjero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
                ('horaRegistro', models.DateTimeField(blank=True, null=True)),
                ('numeroExtranjero', models.IntegerField(blank=True, null=True)),
                ('estacionMigratoria', models.CharField(blank=True, max_length=50)),
                ('nombreExtranjero', models.CharField(blank=True, max_length=50)),
                ('apellidoPaternoExtranjero', models.CharField(blank=True, max_length=50)),
                ('apellidoMaternoExtranjero', models.CharField(blank=True, max_length=50)),
                ('firmaExtranjero', models.FileField(blank=True, null=True, upload_to='files')),
                ('huellaExtranjero', models.FileField(blank=True, null=True, upload_to='files')),
                ('genero', models.IntegerField(choices=[[0, 'HOMBRE'], [1, 'MUJER']])),
                ('fechaNacimiento', models.DateField()),
                ('documentoIdentidad', models.FileField(blank=True, null=True, upload_to='files')),
                ('fotografiaExtranjero', models.FileField(blank=True, null=True, upload_to='files')),
                ('viajaSolo', models.BooleanField()),
                ('tipoEstancia', models.CharField(blank=True, max_length=50)),
                ('deLaPuestaAC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigilancia.puestadisposicionac')),
                ('deLaPuestaIMN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigilancia.puestadisposicioninm')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilancia.nacionalidad')),
            ],
            options={
                'verbose_name_plural': 'Extranjeros',
            },
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delExtranjero', models.IntegerField()),
                ('relacion', models.IntegerField(choices=[[0, 'ESPOSO(A)'], [1, 'HIJO(A)'], [2, 'MADRE'], [3, 'PADRE'], [4, 'OTRO']])),
                ('delAcompanante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigilancia.extranjero')),
            ],
            options={
                'verbose_name_plural': 'Acompañantes',
            },
        ),
    ]
