# Generated by Django 4.2 on 2023-08-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparecencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaComparecencia', models.DateField(verbose_name='Fecha Comparecencia')),
                ('horaComparecencia', models.DateTimeField(verbose_name='Hora Comparecencia')),
                ('estadoCivil', models.IntegerField(choices=[[0, 'Casado(a)'], [1, 'Soltero(a)'], [2, 'Viudo(a)'], [3, 'Divorciado(a)'], [4, 'Separado(a)']], verbose_name='Estado Civil')),
                ('escolaridad', models.IntegerField(choices=[[0, 'Presscolar'], [1, 'Primaria'], [2, 'Secundaria'], [3, 'Preparatoria'], [4, 'Universidad']], verbose_name='Escolaridad')),
                ('ocupacion', models.CharField(max_length=50, verbose_name='Ocupación')),
                ('lugarOrigen', models.CharField(max_length=50, verbose_name='Lugar de Origen')),
                ('calleDomicilioPais', models.CharField(max_length=50, verbose_name='Calle')),
                ('numeroDomicilioPais', models.IntegerField(verbose_name='Numero')),
                ('localidadPais', models.CharField(max_length=50, verbose_name='Localidad')),
                ('domicilioEnMexico', models.BooleanField(verbose_name='Domicilio en México')),
                ('nombrePadre', models.CharField(max_length=50, verbose_name='Nombre del Padre')),
                ('apellidoPaternoPadre', models.CharField(max_length=50, verbose_name='Apellido Paterno del Padre')),
                ('apellidoMaternoPadre', models.CharField(max_length=50, verbose_name='Apellido Materno del Padre')),
                ('nombreMadre', models.CharField(max_length=50, verbose_name='Nombre de la Madre')),
                ('apellidoPaternoMadre', models.CharField(max_length=50, verbose_name='Apellido Paterno de la Madre')),
                ('apellidoMaternoMadre', models.CharField(max_length=50, verbose_name='Apellido Materno de la Madre')),
            ],
        ),
    ]
