# Generated by Django 4.2 on 2023-08-13 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEvento', models.DateField(verbose_name='Fecha Evento')),
                ('horaEvento', models.DateTimeField(verbose_name='Fecha Evento')),
                ('firmaResponsable', models.BinaryField(verbose_name='Firma del Responsable')),
                ('huellaResponsable', models.BinaryField(verbose_name='Huella del Responsable')),
            ],
            options={
                'verbose_name_plural': 'Box Lunches',
            },
        ),
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEvento', models.DateField(verbose_name='Fecha Evento')),
                ('horaEvento', models.DateTimeField(verbose_name='Hora Evento')),
                ('comida', models.BooleanField(verbose_name='Comida')),
                ('desayuno', models.BooleanField(verbose_name='Desayuno')),
                ('cena', models.BooleanField(verbose_name='Cena')),
                ('firmaExtranjero', models.BinaryField(verbose_name='Firma del Extranjero')),
                ('huellaExtranjero', models.BinaryField(verbose_name='Huella del Extranjero')),
            ],
            options={
                'verbose_name_plural': 'Comedores',
            },
        ),
        migrations.CreateModel(
            name='TipoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Dieta')),
                ('caracteristicas', models.TextField(verbose_name='Caracteristicas de la Dieta')),
                ('region', models.CharField(max_length=200, verbose_name='Región de donde proviene')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Dietas',
            },
        ),
        migrations.CreateModel(
            name='Dietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.tipodieta', verbose_name='Tipo de Dieta')),
            ],
            options={
                'verbose_name_plural': 'Dietas',
            },
        ),
    ]
